name: todo1st
description: A todo app.

publish_to: 'none'

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  animations: ^2.0.2
  bloc: ^8.0.3
  dartz: ^0.10.1
  flutter_bloc: ^8.0.1
  flutter_modular: ^4.5.1+1
  flutter_svg: ^1.0.3
  firebase_analytics: ^9.1.4
  firebase_core: ^1.14.0
  firebase_crashlytics: ^2.6.1
  firebase_remote_config: ^2.0.3
  sembast: ^3.2.0
  sembast_sqflite: ^2.0.1
  sembast_web: ^2.0.1+1
  shared_preferences: ^2.0.13
  sqflite: ^2.0.2
  uuid: ^3.0.6

dev_dependencies:
  bloc_test: ^9.0.3

  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

  integration_test:
    sdk: flutter

  modular_test: ^1.0.1+2
  mocktail: ^0.3.0
  dart_code_metrics: ^4.12.0

flutter:
  uses-material-design: true
  assets:
    - images/
