name: todo1st
description: A todo app.

publish_to: 'none'

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.0.3
  # cupertino_icons: ^1.0.4
  # dartx: ^1.0.0
  dartz: ^0.10.1
  flutter_bloc: ^8.0.1
  flutter_modular: ^4.5.0
  # firebase_analytics: ^9.1.0
  # firebase_app_check: ^0.0.6+5
  firebase_core: ^1.13.1
  # firebase_crashlytics: ^2.5.1
  # firebase_remote_config: ^2.0.0
  # firebase_performance: ^0.8.0+5
  json_annotation: ^4.4.0
  sembast: ^3.2.0
  sembast_sqflite: ^2.0.1
  sembast_web: ^2.0.1+1
  # shared_preferences: ^2.0.13
  uuid: ^3.0.6

  tekartik_app_flutter_sembast:
    git:
      url: https://github.com/tekartik/app_flutter_utils.dart
      ref: dart2_3
      path: app_sembast
    version: '>=0.1.0'
  tekartik_app_flutter_sqflite:
    git:
      url: https://github.com/tekartik/app_flutter_utils.dart
      ref: dart2_3
      path: app_sqflite
    version: '>=0.2.0'

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.1.7

  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  freezed: 1.1.0
  freezed_annotation: ^1.1.0

  integration_test:
    sdk: flutter

  json_serializable: ^6.1.4
  modular_codegen: ^3.0.4
  modular_test: ^1.0.1+1
  mocktail: ^0.3.0
  mockito: ^5.1.0

flutter:
  uses-material-design: true

  assets:
    - images/

vars:
  replace: --delete-conflicting-outputs
  runner: flutter pub run build_runner

scripts:
  rbuild: $runner build $replace
  rwatch: $runner watch $replace
