name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v2
      - name: Flutter action
        uses: subosito/flutter-action@v2.3.0
        with:
          cache: true
          cache-key: flutter-cache
          cache-path: ${{ runner.tool_cache }}/flutter
      - name: Install dependencies
        run: flutter pub get
      - name: Verify formatting
        run: flutter format --output=none --set-exit-if-changed .
      - name: Generate Code with build_runner
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Analyze project source
        run: flutter analyze .
      - name: Run tests
        run: flutter test
