name: Tests

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    branches: [main]
    paths-ignore:
      - '**.md'
      - 'docs/**'

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.head_ref || github.ref, 'buildfix/') }}
    steps:
      - name: Code checkout
        uses: actions/checkout@v2
      - name: Flutter builder
        uses: subosito/flutter-action@v2.3.0
        with:
          cache: true
          cache-key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          cache-path: ${{ runner.tool_cache }}/.pub-cache
          channel: 'stable'
          flutter-version: '2.10.3'
      - name: Create firebase options file
        uses: timheuer/base64-to-file@v1.1
        with:
          fileName: 'lib/firebase_options.dart'
          encodedString: ${{ secrets.FIREBASE_OPTIONS }}
      - name: Verify formatting
        run: flutter format --output=none --set-exit-if-changed .
      - name: Install dependencies
        run: flutter pub get
      - name: Generate code with build_runner
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Analyze project source
        run: flutter analyze .
      - name: Run tests
        run: flutter test
