name: Tests

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    branches: [main]
    paths-ignore:
      - '**.md'
      - 'docs/**'
    branches-ignore:
      - 'buildfix/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v2
      - name: Flutter action
        uses: subosito/flutter-action@v2.3.0
        with:
          cache: true
          cache-key: flutter-cache
          cache-path: ${{ runner.tool_cache }}/flutter
      - name: Create firebase options file
        run: |
          echo $FIREBASE_OPTIONS | base64 -d > lib/firebase_options.dart
          flutter format lib/firebase_options.dart
        env:
          FIREBASE_OPTIONS: ${{ secrets.FIREBASE_OPTIONS }}
      - name: Check firebase options file
        run: cat lib/firebase_options.dart
      - name: Verify formatting
        run: flutter format --output=none --set-exit-if-changed .
      - name: Install dependencies
        run: flutter pub get
      - name: Generate code with build_runner
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Analyze project source
        run: flutter analyze .
      - name: Run tests
        run: flutter test
